-- ============================================================================
-- MiLearn — 25 Real Courses with Module Content
-- Run after 002_full_platform_tables.sql
-- ============================================================================

-- ─── LEGAL & RIGHTS (5 courses) ──────────────────────────────────────────

INSERT INTO courses (id, title, description, category, difficulty, mly_reward, module_count) VALUES
('c001', 'Know Your Rights: Complete Guide', 'A comprehensive guide to your constitutional rights, how to exercise them, and what to do when they''re violated.', 'legal', 'beginner', 15, 10),
('c002', 'Tenant Rights in Florida', 'Everything renters need to know about Florida landlord-tenant law, eviction protections, and how to fight back.', 'legal', 'beginner', 12, 8),
('c003', 'Police Encounters: What to Do', 'Step-by-step guide for traffic stops, pedestrian stops, home visits, and arrest scenarios. Know what to say and when to stay silent.', 'legal', 'beginner', 10, 6),
('c004', 'Small Claims Court: Step by Step', 'How to file, prepare, and win in small claims court without a lawyer. Covers disputes up to $8,000 in Florida.', 'legal', 'intermediate', 12, 7),
('c005', 'Immigration Rights Basics', 'Your rights regardless of immigration status. ICE encounters, workplace rights, family separation resources.', 'legal', 'beginner', 12, 8);

-- Modules for Course 1: Know Your Rights
INSERT INTO course_modules (course_id, position, title, content_md, quiz) VALUES
('c001', 1, 'The Bill of Rights Overview', '# The Bill of Rights\n\nThe first 10 amendments to the Constitution protect your fundamental freedoms.\n\n## Key Takeaway\nThese rights **cannot** be taken away by any government — federal, state, or local. They apply to everyone on US soil, regardless of citizenship status.\n\n## The Big 5 You Need Daily:\n1. **1st Amendment** — Speech, religion, assembly, press\n2. **4th Amendment** — No unreasonable searches\n3. **5th Amendment** — Right to remain silent\n4. **6th Amendment** — Right to a lawyer\n5. **14th Amendment** — Equal protection\n\n## Why This Matters\nPolice, employers, and governments routinely violate these rights because people don''t know they have them. Knowledge is your first defense.', '[{"question":"Can the government restrict your right to protest?","options":["Yes, always","No, never","Only with a permit for public safety","Only during emergencies"],"correct":2},{"question":"Do constitutional rights apply to non-citizens?","options":["No","Yes, most of them","Only the 2nd Amendment","Only to legal residents"],"correct":1}]'),
('c001', 2, 'The 4th Amendment: Searches', '# Your Right Against Unreasonable Search\n\n## The Rule\nPolice CANNOT search you, your home, your car, or your phone without:\n- A warrant signed by a judge, OR\n- Your voluntary consent, OR\n- A recognized exception (plain view, exigent circumstances)\n\n## The Magic Words\n> "I do not consent to a search."\n\nSay it clearly. Say it calmly. Say it on camera if possible.\n\n## What Happens If They Search Anyway?\nDo NOT physically resist. State your objection verbally, then comply physically. The evidence may be thrown out in court later (exclusionary rule).\n\n## Phone Searches\nSince Riley v. California (2014), police need a warrant to search your phone — even during an arrest. Lock your phone with a passcode (not biometrics, which can be compelled).', '[{"question":"What should you say if police ask to search your car?","options":["Sure, I have nothing to hide","I do not consent to a search","You need my lawyer''s permission","I''ll think about it"],"correct":1},{"question":"Can police search your phone during arrest without a warrant?","options":["Yes","No","Only if it''s unlocked","Only for 5 minutes"],"correct":1}]'),
('c001', 3, 'The 5th Amendment: Silence', '# Your Right to Remain Silent\n\n## The Rule\nYou cannot be forced to testify against yourself. This applies:\n- During police questioning\n- During interrogation\n- In court\n- At any government hearing\n\n## How to Invoke It\n> "I am invoking my Fifth Amendment right to remain silent. I want a lawyer."\n\nThen **STOP TALKING**. Completely. Do not:\n- Explain yourself\n- Apologize\n- Make small talk\n- Answer "just one more question"\n\n## Why People Talk\nPolice are trained interrogators. They use:\n- Fake sympathy: "I understand, just explain your side"\n- Lies: "Your friend already told us everything" (legal to lie)\n- Minimization: "It''s not a big deal, just clear it up"\n\nAll designed to make you incriminate yourself.\n\n## The Only Correct Response\nLawyer. Silence. Nothing else.', '[{"question":"After invoking your right to silence, what should you do?","options":["Explain your side briefly","Answer easy questions only","Stop talking completely","Ask what evidence they have"],"correct":2},{"question":"Can police legally lie to you during interrogation?","options":["No, that''s illegal","Yes, it''s allowed","Only federal agents","Only with a warrant"],"correct":1}]'),
('c001', 4, 'The 6th Amendment: Right to Counsel', '# Your Right to a Lawyer\n\n## The Rule\nIf you are arrested or charged with a crime, you have the right to:\n- A lawyer (even if you can''t afford one)\n- Have that lawyer present during questioning\n- A speedy public trial\n- Confront witnesses against you\n\n## How to Get a Public Defender\n1. At your first court appearance (arraignment), tell the judge you cannot afford a lawyer\n2. Fill out the financial affidavit\n3. A public defender will be assigned\n\n## Important: Invoke EARLY\nDon''t wait until court. The moment police contact becomes adversarial:\n> "I want a lawyer."\n\nOnce you say this, they MUST stop questioning you.\n\n## Jacksonville Resources\n- Public Defender: 904-255-4700\n- Jacksonville Area Legal Aid: 904-356-8371\n- Three Rivers Legal Services: 386-752-1011', '[{"question":"When should you ask for a lawyer?","options":["At trial","At arraignment","The moment police questioning becomes adversarial","Only if charged with a felony"],"correct":2}]'),
('c001', 5, 'The 14th Amendment: Equal Protection', '# Equal Protection Under Law\n\n## The Rule\nNo state shall deny any person equal protection of the laws. This means:\n- Police must treat you the same regardless of race\n- City services must be equally distributed across neighborhoods\n- Laws cannot discriminate based on protected characteristics\n\n## Why This Matters for Jacksonville\nIf your neighborhood gets:\n- Slower police response times\n- Worse road maintenance\n- Fewer parks and resources\n- Heavier policing for minor offenses\n\n...compared to wealthier/whiter neighborhoods, that may violate the 14th Amendment.\n\n## How MiLyfe Helps\nMiCity tracks issue resolution times by neighborhood. This data can be used to prove unequal treatment — the first step to legal challenge.\n\n## Filing a Complaint\n- DOJ Civil Rights Division: 1-800-253-3931\n- ACLU of Florida: aclufl.org\n- NAACP Jacksonville Branch: 904-354-1217', '[{"question":"What does the 14th Amendment guarantee?","options":["Right to bear arms","Freedom of speech","Equal protection under law","Right to vote"],"correct":2}]');

-- ─── FINANCIAL (5 courses) ──────────────────────────────────────────

INSERT INTO courses (id, title, description, category, difficulty, mly_reward, module_count) VALUES
('c006', '$MLY Economics: How Community Currency Works', 'Understand the MiLyfe economy — how $MLY is earned, spent, decayed, and why it''s designed to circulate.', 'financial', 'beginner', 8, 5),
('c007', 'Building Credit from Zero', 'A step-by-step guide to establishing credit history, improving your score, and avoiding predatory products.', 'financial', 'beginner', 12, 8),
('c008', 'Starting a Business with $0', 'How to validate, launch, and grow a business with no capital. Leverage community, skills, and platforms.', 'financial', 'intermediate', 15, 10),
('c009', 'Crypto & Digital Assets for Beginners', 'Understand blockchain, Bitcoin, stablecoins, and digital ownership without the hype. Practical knowledge for the real world.', 'financial', 'beginner', 10, 7),
('c010', 'Tax Basics for Gig Workers', 'Self-employment tax, quarterly payments, deductions, and how to not get surprised at tax time.', 'financial', 'intermediate', 10, 6);

INSERT INTO course_modules (course_id, position, title, content_md) VALUES
('c006', 1, 'What is $MLY?', '# Understanding $MLY\n\n$MLY is MiLyfe''s community currency. It is:\n- **Not crypto** — no blockchain, no speculation\n- **Pegged 1:1 to USD** — 1 MLY = $1\n- **Earned, not bought** — you get it by participating\n- **Designed to circulate** — hoarding is taxed\n\n## How You Earn\n- Daily UBI: $10/day for active members\n- Health check-ins: $5/day\n- Reporting issues: $3-10\n- Voting on proposals: $3\n- Publishing content: $5\n- Completing courses: $8-15\n- Guild patrols: $10-30/day\n\n## How You Spend\n- Buy from MiShop\n- Pay local businesses\n- Send to friends/family\n- Tip creators\n- Fund proposals'),
('c006', 2, 'The Decay System', '# Why Your Balance Decreases\n\n## Inactive Decay\nIf you don''t participate for 14+ days, your balance decays at 2% per day.\n\n**Why?** To prevent abandonment. $MLY that sits in dead accounts hurts the community.\n\n## Hoarding Tax\nBalances over $1,000 MLY decay at 1% per day on the excess.\n\n**Why?** To encourage circulation. $MLY is meant to flow through the community, not be hoarded.\n\n## How to Avoid Decay\n- Check in daily (any action counts)\n- Spend at local businesses\n- Send to friends\n- Participate in governance\n\n## Where Decayed MLY Goes\nIt''s burned — permanently removed from supply. This keeps the overall value stable.'),
('c006', 3, 'Spending Smart', '# Where to Spend $MLY\n\n## Local Businesses\nCheck the Business Hub for shops accepting $MLY. Every dollar spent locally is a dollar that stays in our community.\n\n## MiShop\nBuy goods and services from neighbors. From baked goods to tutoring to lawn care.\n\n## Tips & Transfers\nTip content creators. Send $MLY to family. Split costs with roommates.\n\n## Why Spending > Hoarding\nEvery $MLY spent:\n1. Supports a neighbor''s income\n2. Keeps the local economy healthy\n3. Avoids your hoarding tax\n4. Earns you standing points\n\nThe system rewards circulation, not accumulation.');

-- ─── DIGITAL (4 courses) ──────────────────────────────────────────

INSERT INTO courses (id, title, description, category, difficulty, mly_reward, module_count) VALUES
('c011', 'Digital Literacy: Protect Yourself Online', 'Passwords, phishing, privacy settings, and data protection. Essential knowledge for the modern world.', 'digital', 'beginner', 10, 8),
('c012', 'Building Your First Website', 'From zero to published website. No coding experience needed. HTML, hosting, and domains explained simply.', 'digital', 'beginner', 12, 10),
('c013', 'Data Privacy: What They Know About You', 'How companies track you, what data they sell, and practical steps to protect your digital footprint.', 'digital', 'intermediate', 10, 6),
('c014', 'AI Literacy: Understanding Machine Learning', 'What AI actually is, how it works, its limitations, and how it''s being used in your daily life.', 'digital', 'intermediate', 12, 7);

INSERT INTO course_modules (course_id, position, title, content_md) VALUES
('c011', 1, 'Password Security', '# Passwords: Your First Defense\n\n## The Problem\nMost people use:\n- The same password everywhere\n- Short, guessable passwords\n- Personal info (birthdays, pet names)\n\n## The Fix\n1. **Use a password manager** (Bitwarden is free)\n2. **Make passwords 16+ characters**\n3. **Never reuse across sites**\n4. **Enable 2FA everywhere**\n\n## How to Make a Strong Password\nUse a passphrase: 4+ random words strung together\n- Bad: `fluffy123`\n- Good: `correct-horse-battery-staple`\n- Better: `MiLyfe$Platform$Jacksonville$2026`\n\n## If You Get Hacked\n1. Change the compromised password immediately\n2. Change it everywhere else you used it\n3. Enable 2FA\n4. Check haveibeenpwned.com'),
('c011', 2, 'Phishing & Scams', '# Recognizing Phishing\n\n## What is Phishing?\nFake emails, texts, or websites designed to steal your login credentials or personal info.\n\n## Red Flags\n- Urgent language: "Your account will be closed!"\n- Unknown sender with familiar branding\n- Links that don''t match the company''s real domain\n- Requests for passwords or SSN via email\n- Grammar errors in "official" communications\n\n## What to Do\n1. **Don''t click links** in suspicious emails\n2. **Go directly** to the website by typing it yourself\n3. **Check the sender** email address carefully\n4. **When in doubt**, call the company using their official number\n\n## Common Jacksonville Scams\n- Fake JEA shutoff notices\n- "Jury duty" phone calls demanding payment\n- Fake city parking tickets with QR codes\n- Social media "free MLY" schemes');

-- ─── CIVIC (4 courses) ──────────────────────────────────────────

INSERT INTO courses (id, title, description, category, difficulty, mly_reward, module_count) VALUES
('c015', 'How Local Government Actually Works', 'City council, mayor, budget process, and how decisions affecting your neighborhood get made.', 'civic', 'beginner', 12, 8),
('c016', 'Community Organizing 101', 'How to identify issues, build coalitions, run meetings, pressure officials, and create lasting change.', 'civic', 'intermediate', 15, 10),
('c017', 'Running for Local Office', 'Filing requirements, campaign basics, fundraising, and what the job actually entails. You don''t need to be rich.', 'civic', 'advanced', 15, 7),
('c018', 'Grant Writing for Community Projects', 'Find funding sources, write compelling proposals, manage budgets, and report outcomes.', 'civic', 'advanced', 15, 8);

INSERT INTO course_modules (course_id, position, title, content_md) VALUES
('c015', 1, 'Jacksonville City Government Structure', '# How Jax is Governed\n\n## Consolidated Government\nJacksonville is unique — the city and county merged in 1968. One government covers everything.\n\n## Key Players\n- **Mayor** — Executive (elected, 4-year term)\n- **City Council** — 19 members (14 district + 5 at-large)\n- **Constitutional Officers** — Sheriff, Property Appraiser, Clerk, Tax Collector, Supervisor of Elections\n\n## How Decisions Get Made\n1. Issue identified\n2. Council member introduces legislation\n3. Committee review\n4. Full council vote (10 votes to pass)\n5. Mayor signs or vetoes (13 votes to override)\n\n## Your Entry Points\n- City Council meetings: 1st & 3rd Tuesday, 5pm\n- Public comment: 3 minutes to speak on any topic\n- Committee meetings: Where real work happens\n- Your district council member: The person who represents YOUR area'),
('c015', 2, 'The City Budget', '# Following the Money\n\n## Jacksonville Budget (~$1.6 Billion/year)\n- Public Safety (Sheriff + Fire): ~45%\n- Infrastructure (Roads, Water, Parks): ~20%\n- General Government: ~15%\n- Debt Service: ~10%\n- Everything else: ~10%\n\n## Why This Matters\nWhen your street has potholes but the sheriff gets a new helicopter, that''s a budget priority decision. You can influence these.\n\n## Budget Calendar\n- March: Mayor''s budget office starts planning\n- July: Mayor submits proposed budget\n- August-September: Council hearings (PUBLIC)\n- October 1: New fiscal year begins\n\n## How to Participate\n1. Attend budget hearings in August\n2. Submit written comments to your council member\n3. Use MiCity data to show neighborhood investment gaps\n4. Organize neighbors to show up together (numbers matter)');

-- ─── HEALTH (3 courses) ──────────────────────────────────────────

INSERT INTO courses (id, title, description, category, difficulty, mly_reward, module_count) VALUES
('c019', 'Mental Health First Aid', 'Recognize signs of crisis, support someone in distress, and know when/how to get professional help.', 'health', 'beginner', 12, 8),
('c020', 'Nutrition on a Budget', 'Eat well without spending a fortune. Meal planning, food assistance programs, and community resources.', 'health', 'beginner', 8, 6),
('c021', 'CPR & First Aid Basics', 'Learn the basics of emergency response. Hands-only CPR, choking, bleeding, and when to call 911.', 'health', 'beginner', 10, 5);

INSERT INTO course_modules (course_id, position, title, content_md) VALUES
('c019', 1, 'Recognizing a Mental Health Crisis', '# When Someone Needs Help\n\n## Warning Signs\n- Talking about wanting to die or being a burden\n- Withdrawing from activities and people\n- Extreme mood swings\n- Giving away possessions\n- Increased substance use\n- Sleeping too much or too little\n- Expressing hopelessness\n\n## What to Do\n1. **Ask directly**: "Are you thinking about hurting yourself?" (This does NOT plant the idea)\n2. **Listen without judgment**\n3. **Don''t leave them alone** if in immediate danger\n4. **Call 988** (Suicide & Crisis Lifeline) together\n5. **Call 911** if there''s immediate danger\n\n## Jacksonville Resources\n- 988 Suicide & Crisis Lifeline (call or text)\n- Crisis Center: 904-632-0600\n- Mobile Crisis Team: 904-695-9145\n- NAMI Jacksonville: 904-724-7782\n\n## Remember\nYou don''t need to be a therapist. Just being present and connecting them to help can save a life.');

-- ─── CAREER (3 courses) ──────────────────────────────────────────

INSERT INTO courses (id, title, description, category, difficulty, mly_reward, module_count) VALUES
('c022', 'Interview Skills That Actually Work', 'STAR method, common questions, salary negotiation, and how to follow up. Practical tips from hiring managers.', 'career', 'beginner', 10, 6),
('c023', 'Remote Work: Getting Started', 'Find remote jobs, set up your workspace, manage your time, and avoid common pitfalls.', 'career', 'beginner', 10, 7),
('c024', 'Freelancing & Self-Employment', 'Find clients, set rates, manage contracts, handle taxes, and build a sustainable independent career.', 'career', 'intermediate', 12, 9);

INSERT INTO course_modules (course_id, position, title, content_md) VALUES
('c022', 1, 'The STAR Method', '# STAR: How to Answer Any Interview Question\n\n## What is STAR?\nA structured way to answer behavioral interview questions:\n\n- **S**ituation — Set the scene (where, when, what was happening)\n- **T**ask — What was your responsibility?\n- **A**ction — What specifically did YOU do?\n- **R**esult — What happened? (Use numbers if possible)\n\n## Example\n**Q: "Tell me about a time you solved a difficult problem"**\n\n**S:** "At my previous job, our main delivery vendor suddenly went out of business, leaving us with 200 pending orders."\n\n**T:** "As operations lead, I needed to find an alternative within 48 hours or we''d lose those customers."\n\n**A:** "I called 12 local delivery services, negotiated a temporary contract with the best option, personally re-routed the most urgent orders, and set up a tracking system so customers could see status."\n\n**R:** "We fulfilled 195 of 200 orders on time, retained 97% of those customers, and the temp vendor became our permanent partner at 15% lower cost."\n\n## Practice Questions\n1. Tell me about a time you failed\n2. Describe a conflict with a coworker\n3. When did you go above and beyond?\n4. How do you handle tight deadlines?');

-- ─── LIFE SKILLS (2 courses) ──────────────────────────────────────────

INSERT INTO courses (id, title, description, category, difficulty, mly_reward, module_count) VALUES
('c025', 'Conflict Resolution & De-escalation', 'Calm tense situations, mediate disputes, and find solutions without violence. Essential for Guild members.', 'life_skills', 'intermediate', 12, 7),
('c026', 'Home Repair Basics', 'Fix common household problems yourself. Plumbing, electrical, drywall, and when to call a professional.', 'life_skills', 'beginner', 10, 10);

INSERT INTO course_modules (course_id, position, title, content_md) VALUES
('c025', 1, 'The De-escalation Mindset', '# Before Techniques: Your State of Mind\n\n## The Goal\nDe-escalation is NOT about winning. It''s about reducing emotional temperature so rational conversation becomes possible.\n\n## Your Checklist Before Engaging\n1. **Am I calm?** If not, you''ll escalate it further\n2. **Am I safe?** If physical danger exists, create distance first\n3. **What does this person need?** Usually to be heard\n4. **What''s my exit?** Always know how to disengage\n\n## Core Principles\n- **Lower your voice** — people match your energy\n- **Slow down** — speed = anxiety = escalation\n- **Open posture** — uncrossed arms, visible hands\n- **Acknowledge** — "I hear you" is powerful even when you disagree\n- **Name the emotion** — "You seem frustrated" validates without agreeing\n\n## What NOT to Do\n- Don''t say "calm down" (never works)\n- Don''t point or use aggressive body language\n- Don''t interrupt or talk over them\n- Don''t make threats or ultimatums\n- Don''t take insults personally\n\n## The 5-Second Rule\nWhen you feel triggered, count to 5 before responding. Most regrettable things are said in the first 3 seconds.');
